import os
import pandas as pd
import numpy as np

matrix_dir = snakemake.input.matrix_dir
output_file = snakemake.output.mean_matrix
term = snakemake.wildcards.term

print(f"\n--- [Core] Aggregating Mean Adjacencies for {term} ---\n", flush=True)

all_date_dfs = []

# Collect all date matrices generated by the exact math script
parquet_files = [f for f in os.listdir(matrix_dir) if f.endswith('.parquet')]

if not parquet_files:
    raise ValueError(f"No parquet files found in {matrix_dir}\n")

for file in sorted(parquet_files):
    date_str = file.replace('.parquet', '')
    date_int = int(date_str)
    
    file_path = os.path.join(matrix_dir, file)
    df = pd.read_parquet(file_path)
    
    # COMPUTE MEANS
    # Group by Permutation_ID (0 to 1000) and calculate the mean probabilities
    mean_df = df.groupby(level='Permutation_ID').mean()
    
    # RESHAPE
    # Drop the 'Status' level from the columns (Future_Target) so it's just Gene IDs
    if isinstance(mean_df.columns, pd.MultiIndex):
        mean_df.columns = mean_df.columns.get_level_values('Target_ID')
        
    # Transpose the dataframe: Future_Genes become rows, Permutations become columns
    transposed_df = mean_df.T
    
    # Rename columns to requested format: PID0_mean_adj, PID1_mean_adj, etc.
    transposed_df.columns = [f"PID{int(pid)}_mean_adj" for pid in transposed_df.columns]
    
    # Clean up the index so Future_Gene becomes a standard column
    transposed_df.index.name = 'Future_Gene'
    transposed_df = transposed_df.reset_index()
    
    # Add the Date column
    transposed_df['Date'] = date_int
    
    # Reorder columns to strictly match: Date, Future_Gene, PID0_mean_adj, PID1_mean_adj...
    ordered_cols = ['Date', 'Future_Gene'] + [c for c in transposed_df.columns if c.startswith('PID')]
    transposed_df = transposed_df[ordered_cols]
    
    all_date_dfs.append(transposed_df)
    
    print(f"--- [{term}] {date_int} mean adjacencies computed! ---\n", flush=True)
    
print(f"--- [{term}] All mean adjacencies ready! ---\n", flush=True)

# Concatenate all dates into a single massive dataframe
print(f"--- [{term}] Assembling {len(all_date_dfs)} dates into master matrix... ---\n", flush=True)
final_df = pd.concat(all_date_dfs, ignore_index=True)

# Fill NAs with 0.0 (in case a gene wasn't a future target on an earlier date)
final_df = final_df.fillna(0.0)

# --- SORTING ---
# Convert Future_Gene to numeric so it sorts mathematically (e.g., 99 comes before 10013)
final_df['Future_Gene'] = pd.to_numeric(final_df['Future_Gene'])

# Sort chronologically by Date, then numerically by Future_Gene
final_df = final_df.sort_values(by=['Date', 'Future_Gene']).reset_index(drop=True)

# FIX: Downcast to float32 instead of float16 to prevent tiny probabilities from becoming 0.0
float_cols = [c for c in final_df.columns if c.startswith('PID')]
final_df[float_cols] = final_df[float_cols].astype(np.float32)

# Save the consolidated matrix without the pandas index (since it's just row numbers now)
os.makedirs(os.path.dirname(output_file), exist_ok=True)
final_df.to_parquet(output_file, engine='pyarrow', index=False)

print(f"--- [Core] Successfully saved Master Mean Matrix: {output_file} ---\n", flush=True)